### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Mini-Sylar** [Mini-Sylar/Anime-Info-Platform#34]

**Comment by Mini-Sylar** [comment]
I probably should have added a description but

The explanation of every function is found in [Contributions.md](https://github.com/Mini-Sylar/Anime-Info-Platform/blob/master/CONTRIBUTION.md)

Everything concerning how the function is implemented is found in [Index.js](https://github.com/Mini-Sylar/Anime-Info-Platform/blob/master/javascript/index.js)

Let me know if there's anything else!

**Comment by peterebode** [comment]
Okay, I would go through the resource and get started on putting it together..

**Comment by Mini-Sylar** [comment]
A few things i'm thinking we should change
In the README.md there's a section about contributing
since you've added the documentation I think we should update the path to open **En.md** instead of **contribution.MD**

everything in **contribution.md** is in the much better en.md

And there's the title "Anime Streaming Platform", that was a mistake on my part, it's the "Anime Info Platform"

streaming platform was before when i was just making the concept...sorry about that
