### ISSUE TITLE
[Feature] Add anime not found page

### ISSUE THREAD

**Issue by Mini-Sylar** [Mini-Sylar/Anime-Info-Platform#49]
Implement "anime not found page" instead of rolling back to spy x family

**Comment by lodenrogue** [comment]
Seems this is the culprit:

https://github.com/Mini-Sylar/Anime-Info-Platform/blob/7ae11c172521692793e6410077b5c481046a9651/javascript/index.js#L532

**Comment by lodenrogue** [comment]
Addressed in this PR: https://github.com/Mini-Sylar/Anime-Info-Platform/pull/51

No styling added as I'm not a front end specialist but at least it navigates to a not found page.
